version: '3.8'

services:
  app:
    container_name: pdftoolkit-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
    networks:
      - pdftoolkit-network

networks:
  pdftoolkit-network:
    driver: bridge
